### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by ReckerXF** [Stonebound/patreon-to-discord-webhooks#2]
Parse error: syntax error, unexpected 'function' (T_FUNCTION) in /storage/ssd4/217/7045217/public_html/webhook.php on line 8

I uploaded the new file and this happened.

**Comment by phit** [comment]
fixed, forgot a semicolon
https://github.com/Stonebound/patreon-to-discord-webhooks/blob/master/index.php#L5

**Comment by phit** [comment]
ugh did another derp should be good now, sorry

**Comment by ReckerXF** [comment]
Hi, I am now getting these errors:

```
Notice: Undefined index: HTTP_X_PATREON_EVENT in /storage/ssd4/217/7045217/public_html/webhook.php on line 37

Notice: Undefined index: HTTP_X_PATREON_SIGNATURE in /storage/ssd4/217/7045217/public_html/webhook.php on line 38

Warning: hash_equals(): Expected known_string to be a string, null given in /storage/ssd4/217/7045217/public_html/webhook.php on line 42
Patreon Signature didn't match, got: expected: 07b5af3fe0454285991b59572e6e653d`
````
If I send a test through the webhooks page on Patreon it gives me a status 200. I've tested this on two different webservers and it gives the same status 200 error. I've even generated a new webhook.

**Comment by phit** [comment]
mh, thats rather odd
https://github.com/Stonebound/patreon-to-discord-webhooks/blob/master/index.php#L37
this line hasn't changed since the previous version and really should never not work unless something between patreon and your server is eating the headers

**Comment by ReckerXF** [comment]
Well again I tested it between two different webservers and no luck D:

**Comment by phit** [comment]
yeah, and it's working fine for me.. I have really no idea, did the old version work fine?

**Comment by ReckerXF** [comment]
It did before Patreon updated their API lmao

**Comment by Blizzard098** [comment]
Here is my code. Don't care if someone knows the secret because ima revoke it after I show you anyways:
https://hastebin.com/imetagolov.xml

**Comment by phit** [comment]
the old one still works fine! the old api still works it was just deprecated not discontinued
so that basically means the old one was already not working for you for some other reason..

**Comment by ReckerXF** [comment]
le sigh

**Comment by phit** [comment]
add me on discord phit#4970 and I'll try to work this out with you tomorrow, need sleep now
