### ISSUE TITLE
Discord Tag?

### ISSUE THREAD

**Issue by ReckerXF** [Stonebound/patreon-to-discord-webhooks#4]
Hello,

I finally got the webhook working haha. It just took a simple PHP reinstall. Anyways, is it possible to switch the full name with the discord tag they have linked?

Thanks,
Blizzard

**Comment by phit** [comment]
No sorry, not without adding discord API stuff, which I have no interest in.
Patreon only gives you their discord id (not their username#discriminator), for getting those you would need a proper bot user etc..
