### ISSUE TITLE
Patreon has set plegdes:*anything* as Depricated

### ISSUE THREAD

**Issue by AnzoDK** [Stonebound/patreon-to-discord-webhooks#5]
It seems that it might soon stop working

**Comment by phit** [comment]
judging by how broken their v2 api is, not anytime soon, its not even out of beta

> The Patreon Platform is undergoing a version change! V1 is currently our stable version, and V2 is in open beta. Please check back for new functionality, bug fixes, and other API changes.

if you really want v2 for whatever reason, you can use https://github.com/Stonebound/patreon-to-discord-webhooks/blob/58afde14bd7680471aa93721e510fa3fcb712a8a/index.php

but I will only support v1 for now, we've had too many issues in production with v2
