### ISSUE TITLE
Randomly stopped working

### ISSUE THREAD

**Issue by ReckerXF** [Stonebound/patreon-to-discord-webhooks#6]
Hey,

So randomly the script stopped working and giving PHP errors.

> 2019/11/30 03:28:49 [error] 47620#47620: *388463 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: amount_cents in /srv/http/forums/public/discord/webhook.php on line 48PHP message: PHP Notice:  Undefined index: patron in /srv/http/forums/public/discord/webhook.php on line 49PHP message: PHP Notice:  Undefined variable: user_data in /srv/http/forums/public/discord/webhook.php on line 61PHP message: PHP Notice:  Undefined variable: user_data in /srv/http/forums/public/discord/webhook.php on line 62" while reading response header from upstream, client: clientiphere, server: websitehere, request: "POST /discord/webhook.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "websitehere"

**Comment by phit** [comment]
hey sorry for the late reply!
can't reproduce this, however there was a different issue with posting to discord, make sure you got the latest version and are using the deprecated hooks in the Patreon API page
